---
swagger: "2.0"
info:
  version: "1.0.0"
  title: "Code Coverage"
consumes:
  - application/json
produces:
  - application/json
paths:
  /v2/latest:
    get:
      operationId: "code_coverage_backend.api.coverage_latest"
      parameters:
      - name: repository
        in: query
        description: Mozilla repository for these reports (default to mozilla-central)
        required: false
        type: string
      responses:
        200:
          description: Latest coverage builds
      tags:
        - v2

  /v2/path:
    get:
      operationId: "code_coverage_backend.api.coverage_for_path"
      parameters:
      - name: changeset
        in: query
        description: Changeset
        required: false
        type: string
      - name: path
        in: query
        description: File
        required: false
        type: string
      - name: repository
        in: query
        description: Mozilla repository for this changeset (default to mozilla-central)
        required: false
        type: string
      - name: suite
        in: query
        description: Filter the coverage using this test suite
        required: false
        type: string
      - name: platform
        in: query
        description: Filter the coverage using this platform
        required: false
        type: string
      responses:
        200:
          description: Code coverage information for a given file or directory at a given changeset
      tags:
        - v2

  /v2/history:
    get:
      operationId: "code_coverage_backend.api.coverage_history"
      parameters:
      - name: repository
        in: query
        description: Mozilla repository for these reports (default to mozilla-central)
        required: false
        type: string
      - name: start
        in: query
        description: Start timestamp for the history date range (default to a year before end)
        required: false
        type: string
      - name: end
        in: query
        description: End timestamp for the history date range (default to current timestamp)
        required: false
        type: string
      - name: path
        in: query
        description: Path of the repository folder to get coverage info on.
        required: false
        type: string
      - name: suite
        in: query
        description: Filter the coverage using this test suite
        required: false
        type: string
      - name: platform
        in: query
        description: Filter the coverage using this platform
        required: false
        type: string
      responses:
        200:
          description: Overall coverage of specified path over a period of time
      tags:
        - v2

  /v2/extensions:
    get:
      operationId: "code_coverage_backend.api.coverage_supported_extensions"
      responses:
        200:
          description: File extensions supported for code coverage
      tags:
        - v2

  /v2/filters:
    get:
      operationId: "code_coverage_backend.api.coverage_filters"
      parameters:
      - name: repository
        in: query
        description: Mozilla repository for these reports (default to mozilla-central)
        required: false
        type: string
      responses:
        200:
          description: Available filters on the endpoints
      tags:
        - v2
